pub const ZERO: usize = 0;
pub const RA: usize = 1;
pub const SP: usize = 2;
pub const GP: usize = 3;
pub const TP: usize = 4;
pub const T0: usize = 5;
pub const T1: usize = 6;
pub const T2: usize = 7;
pub const S0: usize = 8;
pub const S1: usize = 9;
pub const A0: usize = 10;
pub const A1: usize = 11;
pub const A2: usize = 12;
pub const A3: usize = 13;
pub const A4: usize = 14;
pub const A5: usize = 15;
pub const A6: usize = 16;
pub const A7: usize = 17;
pub const S2: usize = 18;
pub const S3: usize = 19;
pub const S4: usize = 20;
pub const S5: usize = 21;
pub const S6: usize = 22;
pub const S7: usize = 23;
pub const S8: usize = 24;
pub const S9: usize = 25;
pub const S10: usize = 26;
pub const S11: usize = 27;
pub const T3: usize = 28;
pub const T4: usize = 29;
pub const T5: usize = 30;
pub const T6: usize = 31;

pub fn register_name<'a>(register: usize) -> &'a str {
    match register {
        ZERO => "zero",
        RA => "ra",
        SP => "sp",
        GP => "gp",
        TP => "tp",
        T0 => "t0",
        T1 => "t1",
        T2 => "t2",
        S0 => "s0",
        S1 => "s1",
        A0 => "a0",
        A1 => "a1",
        A2 => "a2",
        A3 => "a3",
        A4 => "a4",
        A5 => "a5",
        A6 => "a6",
        A7 => "a7",
        S2 => "s2",
        S3 => "s3",
        S4 => "s4",
        S5 => "s5",
        S6 => "s6",
        S7 => "s7",
        S8 => "s8",
        S9 => "s9",
        S10 => "s10",
        S11 => "s11",
        T3 => "t3",
        T4 => "t4",
        T5 => "t5",
        T6 => "t6",
        _ => "unknown",
    }
}
